# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradle-for-agents" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "e9bd68fd80fe6940ee6cd43d812b069de86f7c87b16c6964d8cf28e677e3c707"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "802a1611ab42c85ec66f84b79012860965f7132a1c525e7c6b98ea74bb4f48a9"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c596dadc8014256ac8fec4c72b62715016f8e0a894c39992fbaf94c4ef748f8f"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "502ead23da4b835a0a5435cc5929e41cbfe8a0db48a553dc7d095fb26b7a0493"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gradle-for-agents"
  desc "Gradle wrapper for AI agents"
  homepage "https://github.com/silverAndroid/gradle-for-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradle-for-agents"
  binary "gfa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradle-for-agents"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gfa"]
    end
  end

  # No zap stanza required

end
