# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradle-for-agents" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ba7954458bad35e6c058c3a68317e2664479de7e8d5efaf5944af12e6317660c"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae00f2b01cb4b9549f8710f492c74bcf82725105f1ff1710a71e7213206b4879"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3962d87951d2ff424adc1a02438b7aff7f9fdebe46d425067bb8efbe1d0e6e0c"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1600065a81648e6e2baa50d62dddcde8bce5b513bb24a36ae9aeb67ecf0d370f"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gradle-for-agents"
  desc "Gradle wrapper for AI agents"
  homepage "https://github.com/silverAndroid/gradle-for-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradle-for-agents"
  binary "gfa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradle-for-agents"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gfa"]
    end
  end

  # No zap stanza required

end
