# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradle-for-agents" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "344aeec4afbad599bf23d2e36b56122f0959beb8221b0e3ece84e9579ed850eb"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62bcd340f1e7900f2c6ac115abc0edc96c1708b0bb817ec4680e60b36f913fca"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8e68749f028f5e34b99cb1c39e70aad5e80e823a1aeeae444172c6c55d6784d"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "637d02f594ddf77ccb4bb4d426769a396c19e4d2a603e49fc6cf83195433f548"
      url "https://github.com/silverAndroid/gradle-for-agents/releases/download/v#{version}/gfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gradle-for-agents"
  desc "Gradle wrapper for AI agents"
  homepage "https://github.com/silverAndroid/gradle-for-agents"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradle-for-agents"
  binary "gfa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradle-for-agents"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gfa"]
    end
  end

  # No zap stanza required

end
